"""agregar tablas faltantes de sprint 0 y 1

Revision ID: b5a1feefa3e6
Revises: 053d503c7eea
Create Date: 2026-09-06 15:57:45.185482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b5a1feefa3e6'
down_revision: Union[str, Sequence[str], None] = '053d503c7eea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categoria',
    sa.Column('idcategoria', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombrecategoria', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('idcategoria')
    )
    op.create_table('certificacion',
    sa.Column('idcertificacion', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('entidademisora', sa.String(length=100), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('logourl', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('idcertificacion')
    )
    op.create_table('permiso',
    sa.Column('idpermiso', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombrepermiso', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.String(length=200), nullable=True),
    sa.Column('modulo', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('idpermiso')
    )
    op.create_table('rol',
    sa.Column('idrol', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombrerol', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('idrol')
    )
    op.create_table('tenant',
    sa.Column('idtenant', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('razonsocial', sa.String(length=100), nullable=False),
    sa.Column('nit', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('configuracion', sa.JSON(), nullable=True),
    sa.Column('fechacreacion', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('idtenant')
    )
    op.create_table('usuario',
    sa.Column('idusuario', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombrecompleto', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('contrasenahash', sa.String(length=255), nullable=False),
    sa.Column('fecharegistro', sa.DateTime(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('idusuario'),
    sa.UniqueConstraint('email')
    )
    op.create_table('actorcadena',
    sa.Column('idactor', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('idtenant', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('razonsocial', sa.String(length=100), nullable=True),
    sa.Column('nit', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('telefono', sa.String(length=50), nullable=True),
    sa.Column('tipoactor', sa.Enum('PROVEEDOR_EEUU', 'TRANSPORTISTA_INTERNACIONAL', 'ADUANA', 'IMPORTADOR', 'DISTRIBUIDOR', 'TIENDA', 'CONSUMIDOR', name='tipo_actor_enum'), nullable=False),
    sa.ForeignKeyConstraint(['idtenant'], ['tenant.idtenant'], ),
    sa.PrimaryKeyConstraint('idactor')
    )
    op.create_table('producto',
    sa.Column('idproducto', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('idcategoria', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('modelo', sa.String(length=50), nullable=True),
    sa.Column('paisorigen', sa.String(length=50), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('imagenurl', sa.String(length=255), nullable=True),
    sa.Column('fechacreacion', sa.DateTime(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['idcategoria'], ['categoria.idcategoria'], ),
    sa.PrimaryKeyConstraint('idproducto')
    )
    op.create_table('rolpermiso',
    sa.Column('idrolpermiso', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('idrol', sa.Integer(), nullable=False),
    sa.Column('idpermiso', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['idpermiso'], ['permiso.idpermiso'], ),
    sa.ForeignKeyConstraint(['idrol'], ['rol.idrol'], ),
    sa.PrimaryKeyConstraint('idrolpermiso')
    )
    op.create_table('tokenrecuperacion',
    sa.Column('idtoken', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('idtenant', sa.Integer(), nullable=True),
    sa.Column('idusuario', sa.Integer(), nullable=False),
    sa.Column('tokenhash', sa.String(length=255), nullable=False),
    sa.Column('expiraen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('usadoen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fechacreacion', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['idtenant'], ['tenant.idtenant'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['idusuario'], ['usuario.idusuario'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('idtoken')
    )
    op.create_table('tokenrefresco',
    sa.Column('idtoken', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('idtenant', sa.Integer(), nullable=True),
    sa.Column('idusuario', sa.Integer(), nullable=False),
    sa.Column('tokenhash', sa.String(length=255), nullable=False),
    sa.Column('expiraen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revocado', sa.Boolean(), nullable=False),
    sa.Column('fechacreacion', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['idtenant'], ['tenant.idtenant'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['idusuario'], ['usuario.idusuario'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('idtoken')
    )
    op.create_table('usuariotenant',
    sa.Column('idusuariotenant', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('idusuario', sa.Integer(), nullable=False),
    sa.Column('idtenant', sa.Integer(), nullable=False),
    sa.Column('fechaasignacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['idtenant'], ['tenant.idtenant'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['idusuario'], ['usuario.idusuario'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('idusuariotenant')
    )
    op.create_table('bitacora',
    sa.Column('idbitacora', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('idusuariotenant', sa.Integer(), nullable=False),
    sa.Column('accion', sa.String(length=50), nullable=False),
    sa.Column('entidad', sa.String(length=50), nullable=False),
    sa.Column('identidad', sa.Integer(), nullable=True),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('fechahora', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['idusuariotenant'], ['usuariotenant.idusuariotenant'], ),
    sa.PrimaryKeyConstraint('idbitacora')
    )
    op.create_table('notificacion',
    sa.Column('idnotificacion', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('idusuariotenant', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=100), nullable=False),
    sa.Column('contenido', sa.Text(), nullable=False),
    sa.Column('leida', sa.Boolean(), nullable=False),
    sa.Column('fechaenvio', sa.DateTime(), nullable=False),
    sa.Column('fechalectura', sa.DateTime(), nullable=True),
    sa.Column('enlaceaccion', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['idusuariotenant'], ['usuariotenant.idusuariotenant'], ),
    sa.PrimaryKeyConstraint('idnotificacion')
    )
    op.create_table('productocertificacion',
    sa.Column('idproductocertificacion', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('idproducto', sa.Integer(), nullable=False),
    sa.Column('idcertificacion', sa.Integer(), nullable=False),
    sa.Column('fechaobtencion', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['idcertificacion'], ['certificacion.idcertificacion'], ),
    sa.ForeignKeyConstraint(['idproducto'], ['producto.idproducto'], ),
    sa.PrimaryKeyConstraint('idproductocertificacion')
    )
    op.create_table('ubicacion',
    sa.Column('idubicacion', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('idtenant', sa.Integer(), nullable=False),
    sa.Column('idactor', sa.Integer(), nullable=True),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('direccion', sa.String(length=255), nullable=True),
    sa.Column('latitud', sa.Numeric(precision=10, scale=8), nullable=True),
    sa.Column('longitud', sa.Numeric(precision=11, scale=8), nullable=True),
    sa.Column('ciudad', sa.String(length=100), nullable=True),
    sa.Column('pais', sa.String(length=100), nullable=True),
    sa.Column('tipo', sa.Enum('origen', 'almacen', 'centro_distribucion', 'punto_venta', 'puerto', 'aduana', name='tipo_ubicacion_enum'), nullable=False),
    sa.ForeignKeyConstraint(['idactor'], ['actorcadena.idactor'], ),
    sa.ForeignKeyConstraint(['idtenant'], ['tenant.idtenant'], ),
    sa.PrimaryKeyConstraint('idubicacion')
    )
    op.create_table('usuariotenantrol',
    sa.Column('idusuariotenantrol', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('idusuariotenant', sa.Integer(), nullable=False),
    sa.Column('idrol', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['idrol'], ['rol.idrol'], ),
    sa.ForeignKeyConstraint(['idusuariotenant'], ['usuariotenant.idusuariotenant'], ),
    sa.PrimaryKeyConstraint('idusuariotenantrol')
    )
    op.create_table('varianteproducto',
    sa.Column('idvariante', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('idproducto', sa.Integer(), nullable=False),
    sa.Column('capacidad', sa.String(length=50), nullable=True),
    sa.Column('color', sa.String(length=50), nullable=True),
    sa.Column('sku', sa.String(length=50), nullable=False),
    sa.Column('preciousd', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['idproducto'], ['producto.idproducto'], ),
    sa.PrimaryKeyConstraint('idvariante'),
    sa.UniqueConstraint('sku')
    )
    op.create_table('catalogotenant',
    sa.Column('idcatalogotenant', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('idtenant', sa.Integer(), nullable=False),
    sa.Column('idvariante', sa.Integer(), nullable=False),
    sa.Column('skuinterno', sa.String(length=50), nullable=True),
    sa.Column('precioventa', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('costopromedio', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['idtenant'], ['tenant.idtenant'], ),
    sa.ForeignKeyConstraint(['idvariante'], ['varianteproducto.idvariante'], ),
    sa.PrimaryKeyConstraint('idcatalogotenant')
    )
    op.create_table('unidadproducto',
    sa.Column('idunidad', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('idtenant', sa.Integer(), nullable=False),
    sa.Column('idvariante', sa.Integer(), nullable=False),
    sa.Column('idrecepciondetalle', sa.Integer(), nullable=True),
    sa.Column('numeroserie', sa.String(length=100), nullable=False),
    sa.Column('imei1', sa.String(length=50), nullable=True),
    sa.Column('imei2', sa.String(length=50), nullable=True),
    sa.Column('eid', sa.String(length=50), nullable=True),
    sa.Column('uuidpublico', sa.String(length=100), nullable=False),
    sa.Column('idcustodioactual', sa.Integer(), nullable=True),
    sa.Column('idubicacionactual', sa.Integer(), nullable=True),
    sa.Column('estado', sa.Enum('disponible', 'vendido', 'en_transito', 'devuelto', 'retirado', name='estado_unidad_enum'), nullable=True),
    sa.Column('fechaingreso', sa.DateTime(), nullable=False),
    sa.Column('fechaventa', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['idcustodioactual'], ['actorcadena.idactor'], ),
    sa.ForeignKeyConstraint(['idtenant'], ['tenant.idtenant'], ),
    sa.ForeignKeyConstraint(['idubicacionactual'], ['ubicacion.idubicacion'], ),
    sa.ForeignKeyConstraint(['idvariante'], ['varianteproducto.idvariante'], ),
    sa.PrimaryKeyConstraint('idunidad')
    )
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_token_hash'), table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tenants_slug'), table_name='tenants')
    op.drop_table('tenants')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('slug', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('tenants_pkey'))
    )
    op.create_index(op.f('ix_tenants_slug'), 'tenants', ['slug'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('last_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('users_tenant_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('users_pkey')),
    sa.UniqueConstraint('tenant_id', 'email', name=op.f('uq_users_tenant_id_email'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('token_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('used_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('password_reset_tokens_tenant_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('password_reset_tokens_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('password_reset_tokens_pkey'))
    )
    op.create_index(op.f('ix_password_reset_tokens_token_hash'), 'password_reset_tokens', ['token_hash'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('token_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('revoked', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('refresh_tokens_tenant_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('refresh_tokens_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('refresh_tokens_pkey'))
    )
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True)
    op.drop_table('unidadproducto')
    op.drop_table('catalogotenant')
    op.drop_table('varianteproducto')
    op.drop_table('usuariotenantrol')
    op.drop_table('ubicacion')
    op.drop_table('productocertificacion')
    op.drop_table('notificacion')
    op.drop_table('bitacora')
    op.drop_table('usuariotenant')
    op.drop_table('tokenrefresco')
    op.drop_table('tokenrecuperacion')
    op.drop_table('rolpermiso')
    op.drop_table('producto')
    op.drop_table('actorcadena')
    op.drop_table('usuario')
    op.drop_table('tenant')
    op.drop_table('rol')
    op.drop_table('permiso')
    op.drop_table('certificacion')
    op.drop_table('categoria')
    # ### end Alembic commands ###
